#!/bin/bash

line=$2

if [ "$line" = "usage" ] || [ $# = 1 ] 
then
  echo "  Follow up on item:"
  curcmd=`basename $0`
  echo "    $curcmd ID [date]"
  echo "       DO that item and create a copy with due [date]. Default is next week."
  echo ""
  exit
fi

if [ $#	= 3 ]
then
	date=$(date --iso-8601 --date="$(echo $3)")
else
	date=$(date --iso-8601 --date="next week")
fi

if [ -z $date ]; then
	exit 2
fi

# we get the text of the item
tofollowup=$(head -n $line $TODO_FILE | tail -n 1)
# we remove the priority
tofollowup=$(sed 's/^([A-Z]) //' <(echo $tofollowup))
# we remove the creation date
tofollowup=$(sed 's/[0-9,-]\+ //' <(echo $tofollowup))
# we DO the item
$TODO_SH command do $line
# add new follow up item
output=$($TODO_SH command add "@followup $tofollowup t:$date")
# prioritize it
tasknumber=$(cut -d' ' <(echo $output) -f 1)
$TODO_SH command pri $tasknumber a
