#!/bin/bash

line=$2

if [ "$line" = "usage" ] || [ $# = 1 ] 
then
  echo "  Follow up on item:"
  echo "    followup ID [date]"
  echo "   default date is next week"
  echo ""
  exit
fi

if [ $#	= 3 ]
then
	date=$(date --iso-8601 --date="$(echo $3)")
else
	date=$(date --iso-8601 --date="next week")
fi

# we get the text of the item
tofollowup=$(head -n "$line" "$TODO_FILE" | tail -n 1)
# we remove the priority
tofollowup=$(sed 's/^([A-Z]) //' <(echo $tofollowup))
# we remove the creation date
tofollowup=$(sed 's/[0-9,-]\+ //' <(echo $tofollowup))
# we DO the item
"$TODO_SH" command do "$line"
# add new follow up item
"$TODO_SH" command add "(A) @followup: $tofollowup t:$date"
